<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita8956b11add8132be7cc75c019e763ae
{
    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'BraintreeHttp\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'BraintreeHttp\\' => 
        array (
            0 => __DIR__ . '/..',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita8956b11add8132be7cc75c019e763ae::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita8956b11add8132be7cc75c019e763ae::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
